# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'NewsSample' do
    pod 'Alamofire', '~> 4.7'
    pod 'XCGLogger', '~> 6.0.2'
pod 'Kingfisher', '~> 4.0'
  use_frameworks!

  # Pods for NewsSample

end
